### ISSUE TITLE
Crashes Reaper when opening 2 UIs

### ISSUE THREAD

**Issue by luismrguimaraes** [magnetophon/lamb-rs#10]
Should be easy to recreate, I'm doing it consistently on macOS Ventura and version 7.22 of Reaper.

Every time I try to open the UI of 2 lamb plugins of the same format (2 CLAP or 2 VST3), Reaper crashes. It **doesn't** crash when it's 1 CLAP and 1 VST3.

**Comment by magnetophon** [comment]
Thanks for the report, and sorry for the late reply!

Could you test if [this](https://github.com/magnetophon/lamb-rs/actions/runs/10921167412/artifacts/1947437038) fixes it?

**Comment by luismrguimaraes** [comment]
It does fix it!

**Comment by magnetophon** [comment]
Thanks!
