### ISSUE TITLE
Segfault with VST3 Release build on Linux

### ISSUE THREAD

**Issue by dromer** [magnetophon/lamb-rs#5]
Ran it in carla-single, after a bit of toying with parameters.

Built using the instructions in the Readme on Debian 12/bookworm

```
13:04:53 [ERROR] thread 'unnamed' panicked at 'assertion `left == right` failed
  left: -1
 right: 1': /home/dreamer/.cargo/git/checkouts/nih-plug-a2d2dc277b128e13/bb27497/src/wrapper/vst3/view.rs:482
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: start_thread
             at ./nptl/pthread_create.c:442:8
  14: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

[carla] Carla exception caught: "idle()" in file ../backend/engine/CarlaEngineRunner.cpp, line 108
fatal runtime error: Rust panics must be rethrown
Aborted
```

**Comment by magnetophon** [comment]
Thanks for the report!

I just fixed another crash.
This seems to be a different issue, but just to make sure, could you try running master?
Either self built, or from here:
https://github.com/magnetophon/lamb-rs/actions/runs/8551802118/artifacts/1384091486

Where you using the GUI or the Carla controls?

Also, I made a [milestone](https://github.com/magnetophon/lamb-rs/milestone/1) for V2.0, and put your dark mode suggestion in it! :)

**Comment by dromer** [comment]
I am already on `914b9edd0f957b927d682c88844ac0d097dcb87a`, so the latest main.

I am using `carla-single` which is cli only.

**Comment by magnetophon** [comment]
Hmm, works fine here.  :/
Does the pre-built binary have the same issue?
Can you run other nih plugins, like Spectral Compressor in carla-single?
Does it work in other hosts?

**Comment by dromer** [comment]
I was playing with it and it randomly crashed. I'm unable to cleanly reproduce.

**Comment by magnetophon** [comment]
Gotcha. Thanks.

**Comment by magnetophon** [comment]
Have you used the plugin in the meantime?
Did it ever crash again?

**Comment by dromer** [comment]
Hey, I have not. Will rebuild the latest and poke around again.

Otherwise we can close the issue and can reopen if it resurfaces.

**Comment by magnetophon** [comment]
Please do!
I'll leave the issue open till then.

**Comment by dromer** [comment]
Ok I was able to make it crash briefly, but after that it was fine.

Here the console output:
```
16:35:11 [ERROR] thread 'unnamed' panicked at 'assertion `left == right` failed
  left: -1
 right: 1': /home/dreamer/.cargo/git/checkouts/nih-plug-a2d2dc277b128e13/bb27497/src/wrapper/vst3/view.rs:482
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: start_thread
             at ./nptl/pthread_create.c:442:8
  14: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by magnetophon** [comment]
Thanks!
I have no idea so far, but I'll ask around.

**Comment by dromer** [comment]
Yup.

**Comment by magnetophon** [comment]
Can you run other nih plugins, like Spectral Compressor in carla-single?

**Comment by dromer** [comment]
I'll try building it and see what happens :)

**Comment by dromer** [comment]
Ah, after some poking around the controls Spectral Compressor also segfaults in exactly the same way!

**Comment by magnetophon** [comment]
Thanks for testing!
Does it also crash on certain parameters but not on others?
Could you open an issue at NIH-plug?

**Comment by magnetophon** [comment]
Robbert implemented a possible fix for this.
Does this one still crash?
https://github.com/magnetophon/lamb-rs/actions/runs/8971978769

**Comment by dromer** [comment]
Seems much more stable now! I tried messing around with all the controls for a couple minutes and no crashes at all.

I think it's good :)
